services:
  - type: web
    name: sql-agent-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # You'll set this in Render dashboard
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    branch: main
